### ISSUE TITLE
No files (probably intentional) and also a request

### ISSUE THREAD

**Issue by Aidolii** [uberhalit/SekiroFpsUnlockAndMore#1]
There's currently no files added, I suspect you're aware of this because you're still working on it, but I'm letting you know just in case.

That said, I have a request. Could you have it skip the intro logos, like this mod does for Dark Souls 3? https://github.com/bladecoding/DarkSouls3RemoveIntroScreens/

**Comment by uberhalit** [comment]
You are right, I did some more testing.
Now it's ready: https://github.com/uberhalit/SekiroFpsUnlockAndMore/releases

Regarding the intro/logo skip: this would require to actively replace DLLs the game loads so I won't add it here.

**Comment by Aidolii** [comment]
Well dinput8.dll is a dll most games do not use, and nothing really injects it either since everything uses xinput now. In any case it's moot, since it looks like they released a version today: https://github.com/bladecoding/DarkSouls3RemoveIntroScreens/releases/tag/v1.15c
