### ISSUE TITLE
[Feature Request] Save Counter Stats

### ISSUE THREAD

**Issue by ThEpicspartan** [uberhalit/SekiroFpsUnlockAndMore#14]
First of all: Great Idea to make kill and death counters. Would it be possible to add a possibility to save the counter states? The possible use case would be, for example, to keep the numbers between several live streams.

**Comment by uberhalit** [comment]
Did you even test the utility? The kills/deaths are read from the savegame file.

**Comment by ThEpicspartan** [comment]
I tested it yesterday and the stats vanished once I closed the game - I did not assume it would load it from the save file. Therefore, thanks for answering blazing fast and apology for bothering you :)
