### ISSUE TITLE
Add Custom Resolution Not Showing Added Resolution in Windowed mode

### ISSUE THREAD

**Issue by Forkinator** [uberhalit/SekiroFpsUnlockAndMore#15]
I wanted to add a custom resolution (3840 x 2160)  to play in higher resolution at over 60fps. I have in my Nvidia Control panel set all the DSR resolutions available. My native resolution is 2560 X 1440.  I know it's not much to go by, but here is my NVCP settings for DSR(note, all boxes are checked in the DSR option);

![screenshot 15](https://user-images.githubusercontent.com/26537506/56061514-813a6280-5d1e-11e9-875b-b55792275fdd.jpg)

While the check the box "Add custom resolution" is checked, in windowed mode the app also removes the ability to change my resolution to my native resolution, and keeps me stuck at the list of low resolutions shown in the screenshot below.  The resolutions you see below are the only ones I am able to use when "add custom resolution" is checked in windowed mode;

![screenshot 14](https://user-images.githubusercontent.com/26537506/56061511-7da6db80-5d1e-11e9-884d-452eca114358.jpg)

This may be an intended consequence of the way the game works with the app, or not. I would love to play Sekiro in 4K resolution above 60fps. 

If this is already mentioned somewhere, forgive me and please delete this/mark it as solved.

**Comment by uberhalit** [comment]
Please have a look at Limitations : `your monitor has to natively support your custom resolution otherwise it won't show up correctly`.
This is exactly what you are experiencing here, for a game to support Nvida DSR it has to implement at least a few NVapi calls that Sekiro unfortunatley doesn't do.

**Comment by Forkinator** [comment]
Thanks man. Sorry I didn't read that part. Been so tired lately with work.
