### ISSUE TITLE
Not sure if this is an issue

### ISSUE THREAD

**Issue by Forkinator** [uberhalit/SekiroFpsUnlockAndMore#17]
After opening the fps unlocker (with my settings file containing the following;  
cbBorderless: true  
cbBorderlessStretch: true )

and starting sekiro, a few seconds later(when the game gets patched) the fps unlocker unchecks the boxes for "Borderless Window" and "Fullscreen stretch"

Then, when i exit the unlocker, the above settings change to "false" in the settings file making me have to enable them again next time i start the unlocker. 

Temporarily fixed having to recheck the 2 checkboxes after closing the unlocker by setting the settings file to read only.

**Comment by uberhalit** [comment]
Are you using a custom resolution? If so then this is intended as you can read in the guide you **have** to manually select your custom res first and afterwards tick Borderless. I can't select the resolution from within my utility.

**Comment by Forkinator** [comment]
I am not using custom resolution

**Comment by Forkinator** [comment]
Added my settings file
[SekiroFpsUnlockAndMore.zip](https://github.com/uberhalit/SekiroFpsUnlockAndMore/files/3083166/SekiroFpsUnlockAndMore.zip)

**Comment by uberhalit** [comment]
Fixed in version 1.2.3.0
