### ISSUE TITLE
Taskbar visible after enabling borderless windowed

### ISSUE THREAD

**Issue by Forkinator** [uberhalit/SekiroFpsUnlockAndMore#2]
Not sure what is causing this, but the taskbar is visible after enabling borderless windowed mode. Strange thing though, this only occurs when the app patches the game. 

If i go to game settings, and change to fullscreen, and then back to windowed, it wont show the taskbar. Then, if i press patch the exe for borderless windowed, the taskbar pops up.

https://i.imgur.com/YtRUuko.jpg

Edit: If i go to my taskbar, and have it set to auto hide during "desktop mode", the taskbar disappears, but it will show my desktop everywhere where the taskbar would have been had i not set it to auto hide.  Really hope we can find a fix for this. I play on 2560 x 1440.

I start up the game, check that windowed mode is set, alt tab out, and run the unlocker.  Then i check the box for borderless fullscreen. Then I alt tab back in game.

**Comment by uberhalit** [comment]
Thanks for reporting, fixed with Version [1.0.2.0](https://github.com/uberhalit/SekiroFpsUnlockAndMore/tree/1.0.2.0)
