### ISSUE TITLE
Windows 10 ver. 1903 broke the patch

### ISSUE THREAD

**Issue by Xephrey** [uberhalit/SekiroFpsUnlockAndMore#21]
It appears that Windows version 1903 has broken the patch.

**Comment by uberhalit** [comment]
Yes Microsoft released a broken patch (KB4515384) that screwed up a few utilities (and the serach bar, and the start menu). They admitted it recently and are working on a new KB to fix it, guess it will be fixed with 1909 release this week. For now uninstalling KB4515384 solves this.

**Comment by gamedevsam** [comment]
Has this been fixed? I want to play the game with high FPS, but I'm on Windows 10 1909.

**Comment by uberhalit** [comment]
It has been long fixed by Microsoft, it was a faulty update.
