### ISSUE TITLE
Not very useful if you can't run the game in fullscreen exclusive mode

### ISSUE THREAD

**Issue by Rings4** [uberhalit/SekiroFpsUnlockAndMore#22]
I'd like to know how to go fullscreen exclusive. The game defaults to fullscreen borderless which gives me worse performance than fullscreen exclusive, but can't find a setting to change. I've tried using the launch option "-window-mode exclusive" to no avail. I don't see a setting in the mod either. 

I get 98-102 fps on every graphics preset (min, medium, high, max) because the game is not in fullscreen exclusive. I have a ryzen 7 1800X and GTX 1080TI and run all my games in 120fps max settings. This mod is not very useful if it doesn't let you run the game in fullscreen exclusive as you cannot get a high enough framerate to look smooth.

**Comment by Keith94** [comment]
It should be in the options.

![1920px-Sekiro_graphics_settings](https://user-images.githubusercontent.com/5490615/65926428-0affea00-e3aa-11e9-9ec2-5f8831447029.png)

**Comment by Rings4** [comment]
> 
> 
> It should be in the options.
> 
> ![1920px-Sekiro_graphics_settings](https://user-images.githubusercontent.com/5490615/65926428-0affea00-e3aa-11e9-9ec2-5f8831447029.png)

Like I said, that's fullscreen borderless.

**Comment by Keith94** [comment]
By default it should not be. Are you using a modified EXE?

**Comment by Rings4** [comment]
> 
> 
> By default it should not be. Are you using a modified EXE?

No, should I be?

**Comment by uberhalit** [comment]
Fullscreen is exclusive fullscreen, the game does not even feature a bordeless fullscreen option by default. If you have a look at the features of my utility it lists borderless fullscreen as an option, make sure you have that turned off. Otherwise you are either using a modified exe or a 3rd party program that forces the game into borderless.

**Comment by Rings4** [comment]
> 
> 
> Fullscreen is exclusive fullscreen, the game does not even feature a bordeless fullscreen option by default. If you have a look at the features of my utility it lists borderless fullscreen as an option, make sure you have that turned off. Otherwise you are either using a modified exe or a 3rd party program that forces the game into borderless.

That's weird. Is that really the case? I just uninstalled and reinstalled (redownloaded) the game to be extra sure that it's vanilla, and it still behaves like a borderless game when the "Fullscreen" setting is selected. 

I can click to my second and third monitor just fine without the game minimizing. The cursor freely exits the game screen as though it was a borderless program. And finally, it performs as poorly as one, bottlenecked by the Windows environment: I get the exact same FPS whether my game is on the Min preset of the Max preset, and this FPS is below my screen's 120Hz refresh rate.

**Comment by uberhalit** [comment]
Well thats mostly an issue with your system then. As stated the game runs either in exclusive fullscreen or in bordered window mode. Enabling the 'borderless' option in my utility adds support for borderless fullscreen.

**Comment by Rings4** [comment]
I don't think the game's exclusive fullscreen mode actually works then. I know that I'm not using your utility to force borderless mode, and I get the same symptoms when your utility isn't even running (except max 60fps.)

Would it be possible for you to allow a "forced" fullscreen exclusive mode to your utility that overrides the game's non-functioning fullscreen exclusive mode? Then I could actually use your utility to increase the framerate instead of just getting a stutterfest.

**Comment by uberhalit** [comment]
Please reinstall the game, update Windows & drivers, close all recording programs & overlays etc. I am not going to fix a bug from FromSoftware with my utility.

**Comment by Keith94** [comment]
If you want to force fullscreen in DX11 games, there are some options you can try. However, I can't guarantee they work flawlessly because I didn't test them with Sekiro.

1. When using [Special K Sekiro mod](https://steamcommunity.com/app/814380/discussions/0/1771511442678518064/), after you run the game, edit the `dxgi.ini` and set `SafeFullscreenMode=false` to `SafeFullscreenMode=true`

2. With [3Dmigoto-1.3.16.zip](https://github.com/bo3b/3Dmigoto/releases), copy the `x64` files to game folder, edit `d3dx.ini` and change `full_screen=0` to `full_screen=1` under the `[Device]` section.

**Comment by Rings4** [comment]
> 
> 
> Please reinstall the game, update Windows & drivers, close all recording programs & overlays etc. I am not going to fix a bug from FromSoftware with my utility.

Not sure what reinstalling a freshly installed game would achieve. I've done the other things and same thing happens, no fullscreen exclusive.
Isn't your utility literally made to fix the 60Hz "bug" from FromSoftware? 


> 
> 
> If you want to force fullscreen in DX11 games, there are some options you can try. However, I can't guarantee they work flawlessly because I didn't test them with Sekiro.
> 
>     1. When using [Special K Sekiro mod](https://steamcommunity.com/app/814380/discussions/0/1771511442678518064/), after you run the game, edit the `dxgi.ini` and set `SafeFullscreenMode=false` to `SafeFullscreenMode=true`
> 
>     2. With [3Dmigoto-1.3.16.zip](https://github.com/bo3b/3Dmigoto/releases), copy the `x64` files to game folder, edit `d3dx.ini` and change `full_screen=0` to `full_screen=1` under the `[Device]` section.

Thanks, will try those two methods out.

**Comment by Rings4** [comment]
> 
> 
> If you want to force fullscreen in DX11 games, there are some options you can try. However, I can't guarantee they work flawlessly because I didn't test them with Sekiro.
> 
>     1. When using [Special K Sekiro mod](https://steamcommunity.com/app/814380/discussions/0/1771511442678518064/), after you run the game, edit the `dxgi.ini` and set `SafeFullscreenMode=false` to `SafeFullscreenMode=true`
> 
>     2. With [3Dmigoto-1.3.16.zip](https://github.com/bo3b/3Dmigoto/releases), copy the `x64` files to game folder, edit `d3dx.ini` and change `full_screen=0` to `full_screen=1` under the `[Device]` section.

I tried the Special K mod and it worked perfectly. Smooth 120fps and my game behaved like a fullscreen application. Thank you for this suggestion! I didn't think this game had such a mod, seeing as the mod I'm commenting on right here was the first google result and not the Special K. Very glad I don't have to run an additional application each time I want to play, too.
