### ISSUE TITLE
Add option to disable message box on Death and Kill count file update exception

### ISSUE THREAD

**Issue by markekraus** [uberhalit/SekiroFpsUnlockAndMore#25]
Occasionally, the app will try to update the `DeathCounter.txt` and/or `TotalKillsCounter.txt` file at the same time OBS is reading from the file. This results in the following message box:

The requested operation cannot be performed on a file with a user-mapped section open.

The message box will steal focus from the game when playing in windowed mode. This casues the player character to some times run to their death or other undesirable behavior.

I recommend adding an option to disable the message box or to simply swallow that exception. In death counters I have written, I just swallow the exception because it will likely update the file successfully on the next pass.

**Comment by uberhalit** [comment]
Hello, sorry for the long delay.

Thats a good input, I've fixed it in Release 1.2.5.1.
