### ISSUE TITLE
Hotkeys

### ISSUE THREAD

**Issue by pips-queek** [uberhalit/SekiroFpsUnlockAndMore#27]
Is there a way to add hotkeys to the +- speed buttons? my goal is to run a 'twitch plays sekiro' where chat inputs can increase and decrease speed while i play.

**Comment by uberhalit** [comment]
Hello, 
well yes thats possible. In [Line 125](https://github.com/uberhalit/SekiroFpsUnlockAndMore/blob/master/SekiroFpsUnlockAndMore/MainWindow.xaml.cs#L125) all hotkeys get registered. One may change it to: 
```cs
const uint VK_ADD = 0x6B;
const uint VK_SUBTRACT = 0x6D;
if (!RegisterHotKey(hWnd, 9009, MOD_CONTROL, VK_M) || !RegisterHotKey(hWnd, 9010, MOD_CONTROL, VK_P) || !RegisterHotKey(hWnd, 9011, 0x0000, VK_ADD) || !RegisterHotKey(hWnd, 9012, 0x0000, VK_SUBTRACT))
```
which would give you two more hotkey events '9011' for Numpad+ and '9012' for Numpad-.
These events can be handled like the other two in the message queue then, [line 195](https://github.com/uberhalit/SekiroFpsUnlockAndMore/blob/master/SekiroFpsUnlockAndMore/MainWindow.xaml.cs#L195)
```cs
else if (msg.wParam.ToInt32() == 9011)   // increase speed
{
    handled = true;
    bool isNumber = Int32.TryParse(this.tbGameSpeed.Text, out int gameSpeed);
    if (isNumber)
    {
        this.tbGameSpeed.Text = (gameSpeed + 5).ToString();
        PatchGameSpeed();
    }
}
else if (msg.wParam.ToInt32() == 9012)   // decrease speed
{
    handled = true;
    bool isNumber = Int32.TryParse(this.tbGameSpeed.Text, out int gameSpeed);
    if (isNumber)
    {
        if (gameSpeed < 5)
            gameSpeed = 5;
        this.tbGameSpeed.Text = (gameSpeed - 5).ToString();
        PatchGameSpeed();
    }
}
```

These hotkeys will still be limited to the game running in (borderless) windowed mode though, if you need a build with working hotkeys in fullscreen let me know.

**Comment by pips-queek** [comment]
Wow! Thank you for the in depth response. You've been such a help. I
downloaded the project and changed the code, however I normally use the
.exe on Nexus Mods. How do I turn this code into an executable?

Thank you again for your help!

-kayleigh

**Comment by pips-queek** [comment]
Some quick searching, trial and error, and its working! Your github doesnt
have your icon so I made my own. If you'd like me to use yours feel free to
post it. Thank you again!

-kayleigh
