### ISSUE TITLE
Unknown game version '1.5.0.0'

### ISSUE THREAD

**Issue by Inityx** [uberhalit/SekiroFpsUnlockAndMore#30]
Running version 1.2.5.1:

![image](https://user-images.githubusercontent.com/9056558/97511092-74eb1a00-1943-11eb-8de7-8616316f4b63.png)

After clicking through, the game refuses to patch, with this message in the log:
```
[10/28/2020 5:33:49 PM] death penalties not found...
```

**Comment by XaeroDegreaz** [comment]
Looks like they just [updated the game](https://steamdb.info/app/814380/history/?changeid=9864549) on October 28th, and the game version is now `1.5.0.0`.

These lines show acceptable versions for the patcher:
https://github.com/uberhalit/SekiroFpsUnlockAndMore/blob/53fd55c3b96bc650d3b8a59671366c7b14ffe481/SekiroFpsUnlockAndMore/GameData.cs#L10-L14

These lines perform the version checks:
https://github.com/uberhalit/SekiroFpsUnlockAndMore/blob/53fd55c3b96bc650d3b8a59671366c7b14ffe481/SekiroFpsUnlockAndMore/MainWindow.xaml.cs#L361-L376

These lines deal with the death penalty offset:
https://github.com/uberhalit/SekiroFpsUnlockAndMore/blob/53fd55c3b96bc650d3b8a59671366c7b14ffe481/SekiroFpsUnlockAndMore/MainWindow.xaml.cs#L701-L706

Seems like some work needs to be done :D

**Comment by AlexanderKhrenov** [comment]
https://github.com/AlexanderKhrenov/SekiroFpsUnlockAndMore/blob/master/README.md
made quick fix

**Comment by AlexanderKhrenov** [comment]
just copied this repository, sorry if this was not polite, I will delete it if you (uberhalit) want me to do so.

**Comment by AlexanderKhrenov** [comment]
didn't updated anything but supported game version list, just wanted my sekiro to run faster xd

**Comment by uberhalit** [comment]
Fixed in version 1.2.5.2, updated necessary code for death penalties.
