### ISSUE TITLE
New update

### ISSUE THREAD

**Issue by toth-Daniel** [uberhalit/SekiroFpsUnlockAndMore#32]
Hi! 

The developers just put out a new update and now the patcher is broken again :(

**Comment by uberhalit** [comment]
As far as I can tell, and what my tester said, everything seems to be working just fine. Can you please confirm what exactly isn't working anymore?

**Comment by toth-Daniel** [comment]
When I click on Patch, it doesn't do anything :( Maybe I'm just a moron, but I tried it twice, and it says "patching...", then patched, but neither is the FPS unlocked nor is the game put into borderless mode :/ Lemme try again to be sure though

**Comment by toth-Daniel** [comment]
Okay nvm, it works now xD No idea what I did, but for some reason the unlock fps and borderless fullscreen wasn't ticked. Anyhow, all gucci now, my bad for wasting your time.

**Comment by madscientista** [comment]
I am on the new update, and the death log isn't working at all. I have died more than 3 times it still says 0 and I am in stream version.
