### ISSUE TITLE
Update to game version 1.6.0.0

### ISSUE THREAD

**Issue by sanlf** [uberhalit/SekiroFpsUnlockAndMore#33]
A patch for the game was released the 19th of November 2020 and made some minor fixes. The program doesn't recognize this version and issues the following warning:

![sekiro_fps_unlocker_warning](https://user-images.githubusercontent.com/35877936/101230191-d0739a80-369b-11eb-8c56-0a1dd4cc338e.png)

But if you ignore the warning, nothing seems to break.

Maybe this can be fixed by just adding the new version to the list of recognized versions?

**Comment by AndhikaWB** [comment]
You can also use hex editor to make the warning disappear, here is the step:
1. Use any hex editor app (e.g. [HxD Hex Editor](https://mh-nexus.de/downloads/HxDPortableSetup.zip))
2. Run HxD and select/open (Ctrl + O) Sekiro FPS Unlocker executable
3. Find (Ctrl + F) the keyword `1.5.0.0`, make sure `Unicode (UTF-16 little endian)` is choosen as text encoding
4. Replace `5` (from 1.5.0.0) to `6` (1.6.0.0) for every results that you find (press F6 to go to the next result)
5. Press save (Ctrl + S)
6. ???
7. Profit

Note that this will only bypass the warning.

**Comment by uberhalit** [comment]
The warning will only be displayed **a single time**. So if you are seeing it every starup, then you either delete the config file of the tool every time or you start it from a directory without write access.
