### ISSUE TITLE
Possibility of Linux support?

### ISSUE THREAD

**Issue by sricks** [uberhalit/SekiroFpsUnlockAndMore#36]
Hi, I'm using Arch Linux to play Sekiro right now. Ultrawide seems to work out of the box with the vanilla game (Not sure how??? I set game settings to 2560x1440 windowed and make the window fullscreen and it looks great) but I would really like to use FPS unlocker.

I got the tool to launch, but it always says "no matching process found" or similar so it can't patch the memory.

**Comment by uberhalit** [comment]
Hello, I guess you are using wine? This utility is making heavy usage of WinAPIs, additionally it expects an ordinary windows memory layout for most of its work. I am almost certain that it won't work on linux without a major recode.

**Comment by cmalvi** [comment]
Here a linux version (not mine) that do only fps unlock https://github.com/Lahvuun/sekirofpsunlock
