### ISSUE TITLE
[Feature Request] Option to set refresh rate

### ISSUE THREAD

**Issue by W4RH4WK** [uberhalit/SekiroFpsUnlockAndMore#37]
Using the game's regular full-screen mode, the refresh-rate of the monitor is set to 60 Hz. It would be nice to have this configurable through the tool.

**Comment by uberhalit** [comment]
Please read the guide. You have to force the monitor to run its highest refresh rate via the Nvidia Control panel.

**Comment by W4RH4WK** [comment]
I've read that and the corresponding setting is set to _highest refresh_ rate. Yet, while the game has focus, NVIDIA control panel shows 60 Hz as refresh rate for the monitor.

Do you know, is this just a bug in the control panel? It _feels_ like 60 Hz but I can't think of any way to verify this right now.

![image](https://user-images.githubusercontent.com/328798/118364942-f4b49b00-b59a-11eb-9f02-7966582009c0.png)

![image](https://user-images.githubusercontent.com/328798/118364931-ec5c6000-b59a-11eb-84db-f386b20bdb5d.png)

**Comment by W4RH4WK** [comment]
Oh and yes, I also tried using the NVIDIA Profile Inspector as described in the guide. My monitor normally runs on 100 Hz.

![image](https://user-images.githubusercontent.com/328798/118366594-b1f5c180-b5a0-11eb-8e6c-cc9336db8220.png)

**Comment by W4RH4WK** [comment]
> if your monitor is still locked at 60Hz in fullscreen after this then your only option remaining is to play in windowed mode.

My suggestion is to also patch the parameter that sets the refresh rate when the resolution is set. I've created a simple interceptor DLL that does that.

https://github.com/W4RH4WK/Sekiro-Refresh-Rate-Fix/blob/f13cc983313785eea421a365344235f20436ed33/src/dxgi_swap_chain.hpp#L128-L130
