### ISSUE TITLE
True FOV adjustment without modifying camera distance

### ISSUE THREAD

**Issue by realnc** [uberhalit/SekiroFpsUnlockAndMore#38]
Hello. Thanks for this tool! Especially the ability to disable auto adjustment of the camera when using the mouse is a huge improvement.

Everything works perfectly overall, except for the FOV adjustment function. Unfortunately, increasing the FOV moves the character further away, making it not that useful. Is it possible to increase the FOV but keep the camera close? Here is an example from a Witcher 3 mod (Absolute Camera). This mod allows you to change both the camera distance, as well as the FOV. So by decreasing camera distance but increasing FOV, I can get this result:

Low FOV:
![LowFOV](https://user-images.githubusercontent.com/1665903/122733411-d1f66000-d285-11eb-8fbd-22385d12027d.jpg)

High FOV:
![HighFOV](https://user-images.githubusercontent.com/1665903/122733465-de7ab880-d285-11eb-9a8d-03fdd89b3306.jpg)

Which keeps the camera close to the player character, but you still have a higher FOV and the game world doesn't appear zoomed-in anymore.

It would be great if your tool could offer this as well.

**Comment by uberhalit** [comment]
Hi, 
now as far as I remember the engine does not offer any additional control over FOV/camera distance, the FOV that we can control is already a huge hack to begin with. Feel free to reverse the games' exe though, I haven't looked into it in quiet some time now so maybe my memory is blurred.
