### ISSUE TITLE
Question regarding saves

### ISSUE THREAD

**Issue by Aidolii** [uberhalit/SekiroFpsUnlockAndMore#4]
Are you positive that the FOV changes do not impact saves whatsoever? I ask because when I save, the game remembers the way I was oriented, even if I've restarted the game since.

If there is even a slight change to the data, even though it reverts on every launch, it could potentially mean that if someone doesn't upgrade before saving with default FOV, the save could get corrupted.

**Comment by uberhalit** [comment]
Hi
FOV is not saved to the game file but you are right about the rotation being saved. As FOV is fixed in vanilla game it wouln't make a lot of sense to even save it in the first place.
