### ISSUE TITLE
[Feature Request] Reset Patcher status automatically

### ISSUE THREAD

**Issue by Aidolii** [uberhalit/SekiroFpsUnlockAndMore#5]
Could you have your tool detect when sekiro.exe has been closed, so if the game is started back up, the autopatcher will do its thing again?

**Comment by uberhalit** [comment]
Thats already in but in order to save performance the auto-job stops checking for game as soon as the game has been found. Simply click "Patch game" when you have closed the game or even have the new instance of the game already open and you are good to go again.
