### ISSUE TITLE
[Feature Request] More negative zoom levels

### ISSUE THREAD

**Issue by Aidolii** [uberhalit/SekiroFpsUnlockAndMore#6]
I'm finding the negative zoom level to be useful for certain bosses, but there's nothing between -10 and -50.

**Comment by uberhalit** [comment]
I am sorry but thats because the game does not support it without extensive patching, there is a premade FOV calculation table in games memory and we can only use these values and nothing else.

**Comment by uberhalit** [comment]
FOV can be changed continuously from -95% to +95% with Version 1.2.2.0
