### ISSUE TITLE
"FOV patch resets after save game reload"

### ISSUE THREAD

**Issue by Keith94** [uberhalit/SekiroFpsUnlockAndMore#7]
Is it possible to freeze the value so this bug doesn't happen?

**Comment by uberhalit** [comment]
As the game does not store the FOV value anywhere it also does not read it from save file of configuration therefore it will reset back to default value whenever any loading happens. The only way to properly solve that is to either overwrite the function that resets the FOV in game's memory or to constantly re-write set FOV value back to memory. I'll think about them.

**Comment by Keith94** [comment]
The FOV is technically stored in the .exe file, right? So patching the bytes directly will change it permanently, but that's not what this app is trying to achieve. 😛 

>I'll think about them.

Sounds good!

**Comment by uberhalit** [comment]
Solved in Version 1.1.0.0
