### ISSUE TITLE
App does not open

### ISSUE THREAD

**Issue by scorthyn** [uberhalit/SekiroFpsUnlockAndMore#9]
Nothing happens when I run it as admin or even normal. Checked AV and it's not stopping it either. Do i need to run the game first then the patch for the window to open?

**Comment by uberhalit** [comment]
HI,
that sounds rather strange. What OS version are you using and do you have .NET Framework 4.0 installed?

**Comment by scorthyn** [comment]
Windows 10 insider build 18865, everything is okay but the app simply doesn't open. Have all the requirements installed

**Comment by uberhalit** [comment]
Unfortunately Microsoft has made quiet a few breaking changes in newer Insider Builds. If you have VS2017 installed you could try to build the app yourself, set a breakpoint `InitializeComponent();` in `MainWindow.xaml.cs` and then single-step through the program to see where it force closes or crashes.

**Comment by uberhalit** [comment]
For anyone coming by here this seems to be a problem of a corrupted microsoft visual c++ 2017 redistributable package and reinstalling it should fix the force close.
